"""add_phase0b_assessment_columns_to_student_profiles

Revision ID: ab05dd3617b7
Revises: a09bedc067be
Create Date: 2026-05-12 03:32:26.045750

NOTE: This migration was generated by alembic autogenerate and manually
curated to remove unwanted DROP statements.
Autogenerate detected DROP TABLE for LangGraph AsyncPostgresSaver checkpoint
tables (created at runtime, not tracked by Alembic), DROP INDEX for manually
added application indexes, and DROP COLUMN for curriculum_level (exists in
Supabase but not in the ORM model — known gap from supabase-setup-log-2026-04-20).
All of those statements were removed. Only the 6 Phase 0b ADD COLUMN statements remain.

This migration is NOT applied via alembic upgrade head.
Apply via Supabase SQL Editor — see SCHEMA_CONTRACT.md Phase 0b instructions.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ab05dd3617b7'
down_revision: Union[str, None] = 'a09bedc067be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('student_profiles', sa.Column('aptitude_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('student_profiles', sa.Column('caas_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('student_profiles', sa.Column('vna_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('student_profiles', sa.Column('family_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('student_profiles', sa.Column('prestige_preference', sa.Float(), nullable=False))
    op.add_column('student_profiles', sa.Column('misc_assessment_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False))


def downgrade() -> None:
    op.drop_column('student_profiles', 'misc_assessment_scores')
    op.drop_column('student_profiles', 'prestige_preference')
    op.drop_column('student_profiles', 'family_context')
    op.drop_column('student_profiles', 'vna_scores')
    op.drop_column('student_profiles', 'caas_scores')
    op.drop_column('student_profiles', 'aptitude_scores')
